spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: scaa
          uri: lb://scaa
          predicates:
            - Path=/servcad/**
        - id: pagamento-assinatura
          uri: lb://pagamento-assinatura
          predicates:
            - Path=/registrarpagamento/**
        - id: status-assinatura
          uri: lb://status-assinatura
          predicates:
            - path=/invalidaass/**
server:
  port: 8765
eureka:
  client:
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}